language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
    - composer self-update

install:
    - composer install --no-interaction --prefer-source

script:
    - ./vendor/bin/phpunit

after_script:
    - ./vendor/bin/coveralls
