language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

install:
  - composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover=./coverage.xml

after_success:
  - >
    wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    && php ./coveralls.phar --verbose
    || true
